spring:
  application:
    name: financial-assistance-scheme-management-system
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Singapore
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/assignmentdb
    username: postgres
    password: admin

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    default-schema: public
    sql-migration-prefix: V
    baseline-version: 1

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate: INFO
    org: INFO

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days