spring:
  application:
    name: financial-assistance-scheme-management-system
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Singapore
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/assignmentdb
    username: postgres

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate: INFO
    org: INFO
